### ISSUE TITLE
I Am Stupid

### ISSUE THREAD

**Issue by justbest23** [adamjsturge/xsshunter-go#90]
Heyo. Not a feature request or a bug. I am finding it impossible to get this to run on my machine.

I am new to using docker so it's probably something I'm doing wrong. I'm using your example compose file from the github page. 

I get the following when I go to the IP, which I guess is expected:

![image](https://github.com/user-attachments/assets/d4f491c8-468b-4243-b972-e9df6144a376)

But when I append "admin" to the IP I get to this page:

![image](https://github.com/user-attachments/assets/d992bc82-f2c8-425c-a2fc-3d69f0390c6c)

I copied the password that the terminal gave me, but nothing happens. It just reloads the page. No error or anything.

Any help is greatly appreciated!

**Comment by justbest23** [comment]
Well it seems that when I connect to it through my proxy it works fine, but not when I try to access the IP directly. So problem solved!

**Comment by adamjsturge** [comment]
You're also no stupid! Docker is pretty complicated and I'm constantly working on making the instructions more clear to set this up. I'm glad you were able to get it to work! Let me know if you need anything and I'll be happy to help
